# Generated by Django 4.0.2 on 2022-06-17 18:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 18, 16, 10, 166914, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_modified_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 18, 16, 10, 166955, tzinfo=utc)),
        ),
    ]
