# Generated by Django 4.0.2 on 2022-07-02 18:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_created_at_alter_task_last_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 18, 21, 27, 703513, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_modified_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 18, 21, 27, 703558, tzinfo=utc)),
        ),
    ]
