# Generated by Django 4.0.2 on 2022-07-22 16:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_task_created_at_alter_task_last_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 22, 16, 36, 49, 214731, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_modified_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 22, 16, 36, 49, 214771, tzinfo=utc)),
        ),
    ]
