# Generated by Django 4.0.2 on 2022-07-22 17:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0009_alter_task_created_at_alter_task_last_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskmaster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 22, 17, 4, 3, 323634, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_modified_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 22, 17, 4, 3, 323669, tzinfo=utc)),
        ),
    ]
