# Generated by Django 4.0.2 on 2022-07-22 18:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_alter_task_created_at_alter_task_last_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 22, 18, 19, 1, 220486, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_modified_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 22, 18, 19, 1, 220521, tzinfo=utc)),
        ),
    ]
