# Generated by Django 4.0.2 on 2022-02-13 10:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp_backend', '0003_alter_task_options_alter_task_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 13, 10, 29, 11, 456693, tzinfo=utc)),
        ),
    ]
