# Generated by Django 4.0.2 on 2022-02-16 15:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp_backend', '0004_alter_task_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_modified_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 16, 15, 58, 36, 982840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 16, 15, 58, 36, 982781, tzinfo=utc)),
        ),
    ]
